export interface Track {
  slug: string
  title: string
  description: string
  level: 'junior' | 'mid' | 'senior'
  challengeSlugs: string[]
}

export const TRACKS: Track[] = [
  // ── Junior ──────────────────────────────────────────────────────────────
  {
    slug: 'javascript-fundamentals',
    title: 'JavaScript Fundamentals',
    description: 'The concepts every JavaScript developer must own: scope, closures, this, and immutability.',
    level: 'junior',
    challengeSlugs: [
      'js-scope-hoisting',
      'js-closures-basics',
      'js-this-binding',
      'js-immutability-basics',
      'js-object-destructuring',
      'js-array-methods',
      'js-error-handling-basics',
      'js-prototype-basics',
      'js-event-loop-basics',
    ],
  },

  // ── Mid ─────────────────────────────────────────────────────────────────
  {
    slug: 'async-mastery',
    title: 'Async Mastery',
    description: 'Promises, async/await, and concurrency patterns. Go from confused to confident with async JavaScript.',
    level: 'mid',
    challengeSlugs: [
      'js-promises-basics',
      'async-promise-chain',
      'async-promise-all-settled',
      'async-serial-execution',
      'async-timeout-race',
      'async-retry',
      'async-error-boundary',
      'promises-concurrency-parallel',
      'error-handling-async-pipeline',
    ],
  },
  {
    slug: 'closures-and-functional',
    title: 'Closures & Functional Patterns',
    description: 'Use closures to build stateful utilities, partial application, and memoization — without classes.',
    level: 'mid',
    challengeSlugs: [
      'closures-counter',
      'closures-once',
      'closures-partial-application',
      'closures-private-state',
      'performance-memoize',
      'performance-debounce',
      'performance-throttle',
      'performance-lru-cache',
    ],
  },
  {
    slug: 'typescript-patterns',
    title: 'TypeScript Patterns',
    description: 'Move beyond basic types. Use generics, utility types, and discriminated unions to write safer code.',
    level: 'mid',
    challengeSlugs: [
      'typescript-generics',
      'typescript-utility-types',
      'typescript-type-guard',
      'typescript-discriminated-union',
      'typescript-overloads',
    ],
  },
  {
    slug: 'testing-craft',
    title: 'Testing Craft',
    description: 'Write tests that actually protect your code. Pure functions, async flows, boundaries, and mocks.',
    level: 'mid',
    challengeSlugs: [
      'testing-pure-functions',
      'testing-boundary-cases',
      'testing-async-function',
      'testing-mock-dependency',
      'testing-tdd-approach',
      'testing-strategy',
    ],
  },
  {
    slug: 'frontend-engineering',
    title: 'Frontend Engineering',
    description: 'DOM patterns, web performance, and accessibility. Build frontends that are fast and usable by everyone.',
    level: 'mid',
    challengeSlugs: [
      'dom-event-delegation',
      'dom-intersection-observer',
      'dom-virtual-list',
      'dom-custom-element',
      'web-performance-rendering',
      'web-performance-core-vitals',
      'web-performance-bundle',
      'accessibility-semantic-html',
      'accessibility-focus-management',
      'accessibility-aria',
    ],
  },
  {
    slug: 'error-handling-and-security',
    title: 'Error Handling & Security',
    description: 'Handle failures gracefully, secure your API, and ship with confidence.',
    level: 'mid',
    challengeSlugs: [
      'error-handling-fetch',
      'error-handling-custom-error',
      'security-sanitize-input',
      'security-csrf-token',
      'security-rate-limit-impl',
      'ci-cd-env-config',
      'api-design-rest-conventions',
      'api-design-error-contracts',
      'api-design-pagination',
    ],
  },

  // ── Senior ───────────────────────────────────────────────────────────────
  {
    slug: 'senior-architecture',
    title: 'Architecture Patterns',
    description: 'Observable, pub-sub, middleware, feature flags, and dependency injection. Patterns that keep large codebases manageable.',
    level: 'senior',
    challengeSlugs: [
      'architecture-event-emitter',
      'architecture-observable',
      'architecture-pub-sub',
      'architecture-middleware',
      'architecture-feature-flags',
      'architecture-dependency-injection',
      'architecture-error-boundaries',
      'architecture-breaking-monolith',
      'refactoring-pure-reducer',
      'refactoring-deep-nesting',
      'refactoring-replace-conditional',
    ],
  },
  {
    slug: 'system-design',
    title: 'System Design',
    description: 'Design systems that scale: caching, queues, search, API versioning, and database schemas.',
    level: 'senior',
    challengeSlugs: [
      'system-design-rate-limit',
      'system-design-caching-strategy',
      'system-design-database-schema',
      'system-design-api-versioning',
      'system-design-background-jobs',
      'system-design-search',
      'tradeoffs-build-vs-buy',
      'tradeoffs-tech-debt',
      'tradeoffs-consistency-availability',
    ],
  },
  {
    slug: 'code-quality',
    title: 'Code Quality & Review',
    description: 'Review code with a senior lens: security issues, performance traps, API design, and test coverage.',
    level: 'senior',
    challengeSlugs: [
      'code-review-pr-feedback',
      'code-review-receiving-feedback',
      'code-review-performance-issue',
      'code-review-security-issue',
      'code-review-api-design',
      'code-review-test-quality',
      'refactoring-when-to-refactor',
      'refactoring-strangler-fig',
      'refactoring-extract-function',
    ],
  },
  {
    slug: 'debugging-and-observability',
    title: 'Debugging & Observability',
    description: 'Find bugs systematically and instrument systems so you understand them in production.',
    level: 'senior',
    challengeSlugs: [
      'debugging-reading-errors',
      'debugging-silent-bug',
      'debugging-flaky-tests',
      'debugging-n-plus-one',
      'debugging-wrong-data',
      'debugging-production-memory-leak',
      'debugging-race-condition',
      'observability-structured-logging',
      'observability-metrics',
      'observability-alerting',
    ],
  },
  {
    slug: 'senior-mindset',
    title: 'Senior Mindset',
    description: 'Communication, estimation, incident response, and documentation. The non-code skills that define senior impact.',
    level: 'senior',
    challengeSlugs: [
      'communication-asking-for-help',
      'communication-scope-creep',
      'communication-disagreeing-with-lead',
      'communication-technical-to-nontechnical',
      'communication-incident-update',
      'communication-postmortem',
      'estimation-first-task',
      'estimation-feature-scoping',
      'estimation-reestimate',
      'estimation-story-points',
      'estimation-unknown-unknowns',
      'incident-response-triage',
      'incident-response-postmortem',
      'incident-response-runbook',
      'documentation-onboarding',
      'documentation-adr',
      'documentation-rfc',
    ],
  },
  {
    slug: 'security-and-mentoring',
    title: 'Security & Mentoring',
    description: 'Defend against real threats, ship safely, and grow the engineers around you.',
    level: 'senior',
    challengeSlugs: [
      'security-api-keys-leaked',
      'security-auth-jwt',
      'security-dependency-audit',
      'security-sensitive-data',
      'ci-cd-pipeline-failure',
      'ci-cd-deploy-strategy',
      'mentoring-junior-stuck',
      'mentoring-onboarding',
      'mentoring-code-standards',
      'mentoring-performance-review',
    ],
  },
]
