export interface Track {
  slug: string
  title: string
  description: string
  level: 'junior' | 'mid' | 'senior'
  challengeSlugs: string[]
}

export const TRACKS: Track[] = [
  {
    slug: 'javascript-fundamentals',
    title: 'JavaScript Fundamentals',
    description: 'The concepts every JavaScript developer must own: scope, closures, this, and immutability.',
    level: 'junior',
    challengeSlugs: [
      'js-scope-hoisting',
      'js-closures-basics',
      'js-this-binding',
      'js-immutability-basics',
      'js-object-destructuring',
      'js-array-methods',
      'js-error-handling-basics',
      'js-prototype-basics',
      'js-event-loop-basics',
    ],
  },
  {
    slug: 'async-mastery',
    title: 'Async Mastery',
    description: 'Promises, async/await, and the event loop. Go from confused to confident with async JavaScript.',
    level: 'mid',
    challengeSlugs: [
      'js-promises-basics',
      'async-promise-chain',
      'async-retry',
      'async-promise-all-settled',
      'async-serial-execution',
      'async-timeout-race',
      'async-error-boundary',
      'error-handling-async-pipeline',
    ],
  },
  {
    slug: 'closures-and-functional',
    title: 'Closures & Functional Patterns',
    description: 'Use closures to build stateful utilities, curried functions, and memoization — without classes.',
    level: 'mid',
    challengeSlugs: [
      'closures-counter',
      'closures-once',
      'closures-partial-application',
      'closures-private-state',
      'performance-memoize',
      'performance-debounce',
      'performance-throttle',
    ],
  },
  {
    slug: 'typescript-patterns',
    title: 'TypeScript Patterns',
    description: 'Move beyond basic types. Use generics, utility types, and discriminated unions to write safer code.',
    level: 'mid',
    challengeSlugs: [
      'typescript-generics',
      'typescript-utility-types',
      'typescript-type-guard',
      'typescript-discriminated-union',
      'typescript-overloads',
    ],
  },
  {
    slug: 'testing-craft',
    title: 'Testing Craft',
    description: 'Write tests that actually protect your code. Pure functions, async flows, boundaries, and mocks.',
    level: 'mid',
    challengeSlugs: [
      'testing-pure-functions',
      'testing-boundary-cases',
      'testing-async-function',
      'testing-mock-dependency',
      'testing-tdd-approach',
      'testing-strategy',
    ],
  },
  {
    slug: 'performance-and-dom',
    title: 'Performance & DOM',
    description: 'Write frontend code that stays fast at scale — debouncing, virtual lists, intersection observers.',
    level: 'mid',
    challengeSlugs: [
      'promises-concurrency-parallel',
      'performance-lru-cache',
      'dom-event-delegation',
      'dom-intersection-observer',
      'dom-virtual-list',
      'dom-custom-element',
    ],
  },
  {
    slug: 'error-handling-and-security',
    title: 'Error Handling & Security',
    description: 'Handle failures gracefully and defend against the most common vulnerabilities.',
    level: 'mid',
    challengeSlugs: [
      'error-handling-fetch',
      'error-handling-custom-error',
      'security-sanitize-input',
      'security-csrf-token',
      'security-rate-limit-impl',
    ],
  },
  {
    slug: 'senior-architecture',
    title: 'Senior Architecture Patterns',
    description: 'Observable, pub-sub, middleware, and dependency injection. The patterns that make large codebases manageable.',
    level: 'senior',
    challengeSlugs: [
      'architecture-event-emitter',
      'architecture-observable',
      'architecture-pub-sub',
      'architecture-middleware',
      'refactoring-replace-conditional',
      'refactoring-deep-nesting',
      'refactoring-pure-reducer',
    ],
  },
  {
    slug: 'senior-mindset',
    title: 'Senior Mindset',
    description: 'The behaviours that separate seniors from mids: communication, estimation, and handling ambiguity.',
    level: 'senior',
    challengeSlugs: [
      'communication-asking-for-help',
      'estimation-first-task',
      'communication-incident-update',
      'communication-scope-creep',
      'communication-disagreeing-with-lead',
      'communication-technical-to-nontechnical',
      'communication-postmortem',
      'estimation-feature-scoping',
      'estimation-reestimate',
      'estimation-story-points',
      'estimation-unknown-unknowns',
    ],
  },
  {
    slug: 'system-design',
    title: 'System Design',
    description: 'Design systems that scale: caching, queues, search, API versioning, and database schemas.',
    level: 'senior',
    challengeSlugs: [
      'system-design-rate-limit',
      'system-design-caching-strategy',
      'system-design-database-schema',
      'system-design-api-versioning',
      'system-design-background-jobs',
      'system-design-search',
    ],
  },
  {
    slug: 'code-quality',
    title: 'Code Quality & Review',
    description: 'Review code with a senior lens: security issues, performance problems, API design, and test coverage.',
    level: 'senior',
    challengeSlugs: [
      'code-review-pr-feedback',
      'code-review-receiving-feedback',
      'code-review-performance-issue',
      'code-review-security-issue',
      'code-review-api-design',
      'code-review-test-quality',
      'refactoring-when-to-refactor',
      'refactoring-strangler-fig',
    ],
  },
  {
    slug: 'debugging-mastery',
    title: 'Debugging Mastery',
    description: 'Systematic debugging: silent failures, N+1 queries, memory leaks, race conditions, and data leaks.',
    level: 'senior',
    challengeSlugs: [
      'debugging-silent-bug',
      'debugging-reading-errors',
      'debugging-flaky-tests',
      'debugging-n-plus-one',
      'debugging-wrong-data',
      'debugging-production-memory-leak',
      'debugging-race-condition',
    ],
  },
  {
    slug: 'api-design',
    title: 'API Design',
    description: 'Design APIs that are predictable, versioned, and a pleasure to consume. REST conventions, error contracts, and pagination.',
    level: 'mid',
    challengeSlugs: [
      'api-design-rest-conventions',
      'api-design-error-contracts',
      'api-design-pagination',
      'system-design-api-versioning',
    ],
  },
  {
    slug: 'observability',
    title: 'Observability',
    description: 'Instrument your systems so you can understand them in production. Logging, metrics, and alerting that actually works.',
    level: 'senior',
    challengeSlugs: [
      'observability-structured-logging',
      'observability-metrics',
      'observability-alerting',
    ],
  },
  {
    slug: 'ci-cd',
    title: 'CI/CD & Deployment',
    description: 'Ship safely and often. Fast pipelines, zero-downtime deploys, and secrets management.',
    level: 'mid',
    challengeSlugs: [
      'ci-cd-env-config',
      'ci-cd-pipeline-failure',
      'ci-cd-deploy-strategy',
    ],
  },
  {
    slug: 'tradeoffs',
    title: 'Engineering Tradeoffs',
    description: 'The core senior skill: knowing what to build, what to buy, when to pay debt, and how to reason about distributed systems constraints.',
    level: 'senior',
    challengeSlugs: [
      'tradeoffs-build-vs-buy',
      'tradeoffs-tech-debt',
      'tradeoffs-consistency-availability',
    ],
  },
  {
    slug: 'incident-response',
    title: 'Incident Response',
    description: 'Handle production incidents like a senior: triage under pressure, communicate clearly, and run postmortems that prevent recurrence.',
    level: 'senior',
    challengeSlugs: [
      'incident-response-triage',
      'incident-response-postmortem',
      'incident-response-runbook',
    ],
  },
  {
    slug: 'web-performance',
    title: 'Web Performance',
    description: 'Understand Core Web Vitals, eliminate render-blocking resources, and ship bundles that load fast.',
    level: 'mid',
    challengeSlugs: [
      'web-performance-rendering',
      'web-performance-core-vitals',
      'web-performance-bundle',
    ],
  },
  {
    slug: 'accessibility',
    title: 'Accessibility',
    description: 'Build interfaces everyone can use. Semantic HTML, ARIA patterns, and keyboard focus management.',
    level: 'mid',
    challengeSlugs: [
      'accessibility-semantic-html',
      'accessibility-focus-management',
      'accessibility-aria',
    ],
  },
  {
    slug: 'documentation',
    title: 'Documentation & Decision Records',
    description: 'Write docs that unblock teams, ADRs that stop relitigating decisions, and RFCs that align before code is written.',
    level: 'senior',
    challengeSlugs: [
      'documentation-onboarding',
      'documentation-adr',
      'documentation-rfc',
    ],
  },
  {
    slug: 'leadership-and-security',
    title: 'Leadership & Security',
    description: 'Mentor effectively, handle incidents, and apply security thinking to real engineering decisions.',
    level: 'senior',
    challengeSlugs: [
      'mentoring-junior-stuck',
      'mentoring-onboarding',
      'mentoring-code-standards',
      'mentoring-performance-review',
      'security-api-keys-leaked',
      'security-auth-jwt',
      'security-dependency-audit',
      'security-sensitive-data',
      'architecture-feature-flags',
      'architecture-dependency-injection',
      'architecture-error-boundaries',
      'architecture-breaking-monolith',
    ],
  },
]
